### ISSUE TITLE
copy button causes scrollbar

### ISSUE THREAD

**Issue by mgeier** [cameronraysmith/nbsphinx-template#1]
First of all, thanks for this template repo!

The CSS of the copy buttons isn't quite right, and it currently causes a scrollbar to appear (at least on Firefox):

![image](https://user-images.githubusercontent.com/705404/120079957-c49aeb00-c0b6-11eb-98c8-e6c2cecbb8c4.png)

This is especially annoying if there is already a scrollbar for overly long cells, because in that case a second scrollbar is added!

It would be great if that could be fixed in https://github.com/executablebooks/sphinx-copybutton, but in the meantime it's probably better to disable this extension?

**Comment by cameronraysmith** [comment]
Thank you @mgeier for https://github.com/spatialaudio/nbsphinx! It looks like this may be related to https://github.com/executablebooks/sphinx-copybutton/issues/71 and https://github.com/executablebooks/sphinx-copybutton/issues/71#issuecomment-612520843.

Yes I agree. I will comment out the usage of https://github.com/executablebooks/sphinx-copybutton for now.

**Comment by mgeier** [comment]
I've just tried with Chromium, and there also appear double horizontal scrollbars.
